language: rust
rust:
  - stable

sudo: required

addons:
  apt:
    packages:
      - libssl-dev

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

before_script:
  - export PATH=$TRAVIS_HOME/.cargo/bin:$PATH
  - cd code

script:
  - cargo build
  - echo "OK"
  - echo $TRAVIS_HOME

env:
  - RUST_BACKTRACE=1
  - RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
  - PATH=$HOME/.local/bin:$PATH
  - LD_LIBRARY_PATH=/home/travis/lib
  - LIBRARY_PATH=/home/travis/lib
  - PKG_CONFIG_PATH=/home/travis/lib/pkgconfig

before_install: # versions from https://github.com/erickt/rust-zmq/blob/master/.travis.yml
  - git clone https://github.com/leejw51crypto/ChainTravis.git /home/travis/tmpdir
  - cp -Rf /home/travis/tmpdir/* /home/travis
  - sudo cp /home/travis/bin/kcov  /usr/local/bin/
  - sudo cp /home/travis/bin/kcov-system-daemon  /usr/local/bin/
  - echo "kcov is successfully installed"
  - cargo-kcov --version || cargo install cargo-kcov;
  - echo "done!"

after_success: 
  - |
    echo "build ok, after_success"
  
 