language: rust
rust:
  - stable

sudo: required

addons:
  apt:
    packages:
      - libssl-dev

cache:
  directories:
    - /home/travis/.cache/sccache
    - /home/travis/.cargo
    - /home/travis/.rustup
    - target

before_cache:
  - rm -rf /home/travis/.cargo/registry/src

before_script:
  - export PATH=$TRAVIS_HOME/.cargo/bin:$PATH
  - cd code

script:
  - cargo build
  - echo "OK"
  - echo $TRAVIS_HOME
