sudo: required

addons:
  apt:
    packages:
      - libssl-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libc6-dev

language: rust

# Cache cargo symbols for faster build
cache: cargo

env:
  - RUST_BACKTRACE=1
  - RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
  - PATH=$HOME/.local/bin:$PATH
  - LD_LIBRARY_PATH=$HOME/lib
  - PKG_CONFIG_PATH=$HOME/lib/pkgconfig

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cd code

script:
  - cargo build
  - echo "OK"
