language: rust
rust:
  - stable

sudo: required

addons:
  apt:
    packages:
      - libssl-dev

before_script:
  - export PATH=$TRAVIS_HOME/.cargo/bin:$PATH
  - cd code

script:
  - cargo build
  - echo "OK"
  - echo $TRAVIS_HOME
